export { default as useDebounce } from './useDebounce'
export { default as useLocalStorage } from './useLocalStorage'
export { default as useTrendingMovies } from './useTrendingMovies'
export { default as useSearchMovies } from './useSearchMovies'
export { default as useMovieDetails } from './useMovieDetails'
export { default as useWatchlist } from './useWatchlist'
