export { default as HomePage } from './HomePage'
export { default as SearchPage } from './SearchPage'
export { default as MovieDetailsPage } from './MovieDetailsPage'
export { default as WatchlistPage } from './WatchlistPage'
export { default as NotFoundPage } from './NotFoundPage'
